=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/codeDefinitions.dtd
<!-- This is a DTD for the <codeDefinitions> vocabulary, exactly as we -->
<!-- received it from Sunrise.  The attribute list for the <line> element -->
<!-- is incredibly loose. -->

<!ELEMENT codeDefinitions (codeBlock)>

<!ELEMENT codeBlock (code*)>

<!ELEMENT code (line*)>
<!ATTLIST code
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
>

<!ELEMENT line EMPTY>
<!ATTLIST line
  action (W | WMAN | R | WREG | WREGMAN | WCFG | LREG.b_L | LREG.b_H | W.b_L
    | W.b_H) #IMPLIED
  code CDATA #IMPLIED
  label CDATA #IMPLIED
  include CDATA #IMPLIED
  comment CDATA #IMPLIED
  register CDATA #IMPLIED
  mask CDATA #IMPLIED
  RWMEnabled CDATA #IMPLIED
  value CDATA #IMPLIED
>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/PIC18F4680 CodeTemplate.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE codeDefinitions SYSTEM "../codeDefinitions.dtd">

<codeDefinitions>

  <codeBlock>

    <code name="fuses" caption="fuses (DCR) configuration">

      <line comment="B7=IESO B6=FCMEN B3:0=FOSC3:0"/>
      <line register="CONFIG1H" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B4:3=BORV1:0 B2:1=BOREN1:0 B0=PWRTEN-L"/>
      <line register="CONFIG2L" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B4:1=WDTPS3:0 B0=WDTEN"/>
      <line register="CONFIG2H" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B7=MCLRE B2=LPT1OSC B1=PBADEN"/>
      <line register="CONFIG3H" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B7=DEBUG-L B6=XINST B5:4=BBSIZ1:2 B2=LVP B0=STVREN"/>
      <line register="CONFIG4L" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B3:0=CP3:0"/>
      <line register="CONFIG5L" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B7=CPD B6=CPB"/>
      <line register="CONFIG5H" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B3:0=WR3:0"/>
      <line register="CONFIG6L" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B7=WRTD B6=WRTB B5=WRTC"/>
      <line register="CONFIG6H" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B3:0=EBTR3:0"/>
      <line register="CONFIG7L" action="WCFG" mask="0x00FF" comment=""/>

      <line comment="B6=EBTRB"/>
      <line register="CONFIG7H" action="WCFG" mask="0x00FF" comment=""/>

    </code>

    <code name="Interrupts" caption="Disable Interrupts during configuration">

      <line comment="B7=IRX B6=WAK B5=ERR B4:2=TXB2:0 B1:0=RXB1:0"/>
      <line register="PIE3" action="W" value="0x0000" mask="0x00FF" comment=""/>
      <line comment="B7=OSCF B6=CM B4=EE B3=BCL B2=LVD B1=TMR3 B0=CCP2"/>
      <line register="PIE2" action="W" value="0x0000" mask="0x00DF" comment=""/>
      <line comment="B7=PSP B6=AD B5=RC1 B4=TX1 B3=SSP B2=CCP1 B1=TMR2 B0=TMR1"/>
      <line register="PIE1" action="W" value="0x0000" mask="0x00FF" comment=""/>

    </code>

    <code name="Oscillator" caption="Oscillator configuration">

      <line comment="B7=IDLEN B6:4=IRCF2:0 B3=OSTS B2=IOFS B1:0=SCS1:0"/>
      <line register="OSCCON" action="WREG" mask="0x00F3" comment=""/>

      <line comment="B7=INTSRC B6=PLLEN B4:0=TUN4:0"/>
      <line register="OSCTUNE" action="WREG" mask="0x00DF" comment=""/>

    </code>

    <code name="Reset" caption="Reset configuration">

      <line comment="B5=IRVST B4=LVDEN B3:0=LVDL3:0"/>
      <line register="LVDCON" action="WREG" mask="0x003F" comment=""/>
      <line comment="B5=IRVST B4=LVDEN B3:0=LVDL3:0"/>
      <line register="WDTCON" action="WREG" mask="0x0001" comment=""/>
      <line comment="B7=IPEN B6=SBOREN B4=RI-L B3=TO-L B2=PD-L B1=POR-L B0=BOR-L"/>
      <line register="RCON" action="WREG" mask="0x00DF" comment=""/>

    </code>

    <code name="IOPortA" caption="IO Ports configuration">

      <line comment="port A is 6 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISA" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTA" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISA" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="IOPortB" caption="IO Ports configuration">

      <line comment="port B is 8 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISB" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTB" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISB" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="IOPortC" caption="IO Ports configuration">

      <line comment="port C is 8 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISC" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTC" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISC" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="IOPortD" caption="IO Ports configuration">

      <line comment="port D is 8 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISD" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTD" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISD" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="IOPortE" caption="IO Ports configuration">

      <line comment="port E is 8 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISE" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTE" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISE" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="IOPortF" caption="IO Ports configuration">

      <line comment="port F is 8 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISF" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTF" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISF" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="IOPortG" caption="IO Ports configuration">

      <line comment="port G is 5 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISG" action="W" value="0x1F" mask="0x001F" comment=""/>
      <line register="PORTG" action="WREG" mask="0x001F" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISG" action="WREG" mask="0x001F" comment=""/>

    </code>

    <code name="IOPortH" caption="IO Ports configuration">

      <line comment="port H is 8 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISH" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTH" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISH" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="IOPortJ" caption="IO Ports configuration">

      <line comment="port J is 8 bits wide"/>
      <line comment="set TRIS to all inputs before setting initial value"/>
      <line register="TRISJ" action="W" value="0xFF" mask="0x00FF" comment=""/>
      <line register="PORTJ" action="WREG" mask="0x00FF" comment=""/>
      <line comment="set port bit as input (1) or output (0)"/>
      <line register="TRISJ" action="WREG" mask="0x00FF" comment=""/>

    </code>

    <code name="PSP" caption="PSP configuration">

      <line comment="part of TRISE: B7=IBF B6=OBF B5=IBOV B4=PSPMODE"/>
      <line comment="TRISE already configured above"/>

    </code>

    <code name="EMI" caption="EMI configuration">

      <line comment="B7=EBDIS B5:4=WAIT1:0 B1:0=WM1:0"/>
      <line register="MEMCON" action="WREG" mask="0x00B3" comment=""/>

    </code>

    <code name="CCP1" caption="CCP configuration">

      <line comment="(H)Register High Byte"/>
      <line comment="(L)Register Low Byte"/>
      <line comment="(CON)B5:4=DCB1:0 B4:0=CCPM3:0"/>
      <line register="CCPR1H" action="WREG" mask="0x00FF" comment=""/>
      <line register="CCPR1L" action="WREG" mask="0x00FF" comment=""/>
      <line register="CCP1CON" action="WREG" mask="0x003F" comment=""/>

    </code>

    <code name="CCP2" caption="ECCP configuration">

      <line comment="(H)Register High Byte"/>
      <line comment="(L)Register Low Byte"/>
      <line comment="(CON)B7:6=PWM1M1:0 B5:4=DCB1:0 B4:0=CCPM3:0"/>
      <line comment="(DEL)B7=PRSEN B6:0=PDC6:0"/>
      <line comment="(AS)B6:4=AS2:0 B3:2=PSSAC1:0 B1:0=PSSBD1:0"/>
      <line register="ECCPR1H" action="WREG" mask="0x00FF" comment=""/>
      <line register="ECCPR1L" action="WREG" mask="0x00FF" comment=""/>
      <line register="ECCP1CON" action="WREG" mask="0x00FF" comment=""/>
      <line register="ECCP1DEL" action="WREG" mask="0x00FF" comment=""/>
      <line register="ECCP1AS" action="WREG" mask="0x007F" comment=""/>

    </code>

    <code name="CCP3" caption="CCP configuration">

      <line comment="(H)Register High Byte"/>
      <line comment="(L)Register Low Byte"/>
      <line comment="(CON)B5:4=DCB1:0 B4:0=CCPM3:0"/>
      <line register="CCPR3H" action="WREG" mask="0x00FF" comment=""/>
      <line register="CCPR3L" action="WREG" mask="0x00FF" comment=""/>
      <line register="CCP3CON" action="WREG" mask="0x003F" comment=""/>

    </code>

    <code name="CCP4" caption="CCP configuration">

      <line comment="(H)Register High Byte"/>
      <line comment="(L)Register Low Byte"/>
      <line comment="(CON)B5:4=DCB1:0 B4:0=CCPM3:0"/>
      <line register="CCPR4H" action="WREG" mask="0x00FF" comment=""/>
      <line register="CCPR4L" action="WREG" mask="0x00FF" comment=""/>
      <line register="CCP4CON" action="WREG" mask="0x003F" comment=""/>

    </code>

    <code name="CCP5" caption="CCP configuration">

      <line comment="(H)Register High Byte"/>
