=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/configurationRegisters.dtd
<!-- Here is yet another DTD for yet another XML vocab we received from -->
<!-- Sunrise.  As with all of the other vocabularies, I made very gentle -->
<!-- modifications to the XML documents to slightly tighten this DTD, but -->
<!-- it would be nice to go farther.  The <sfr> and <field> elements are a -->
<!-- little 'loosey goosey'. -->

<!ELEMENT configurationRegisters (
  specialFunctionRegisters, deviceConfigurationRegisters
)>

<!ELEMENT specialFunctionRegisters (
  CPUCore | InterruptControl | ICN | IOPort | Timers | IC | OC | QEI | PWM
  | SPI | I2C | UART | CAN | DCI | A2D | NVM | reset | oscillator | PMD
  | MSSP | CCP | VoltageRef | Comparator | EMI | PSP | TwoPhasePWM | EEPROM
  | OpAmp)*
>

<!ELEMENT CPUCore (sfr | UnusedRegs)*>
<!ELEMENT InterruptControl (sfr | UnusedRegs)*>
<!ELEMENT ICN (sfr | UnusedRegs)*>
<!ELEMENT IOPort (sfr | UnusedRegs)*>
<!ELEMENT Timers (sfr | UnusedRegs)*>
<!ELEMENT IC (sfr | UnusedRegs)*>
<!ELEMENT OC (sfr | UnusedRegs)*>
<!ELEMENT QEI (sfr | UnusedRegs)*>
<!ELEMENT PWM (sfr | UnusedRegs)*>
<!ELEMENT SPI (sfr | UnusedRegs)*>
<!ELEMENT I2C (sfr | UnusedRegs)*>
<!ELEMENT UART (sfr | UnusedRegs)*>
<!ELEMENT CAN (sfr | UnusedRegs)*>
<!ELEMENT DCI (sfr | UnusedRegs)*>
<!ELEMENT A2D (sfr | UnusedRegs)*>
<!ELEMENT NVM (sfr | UnusedRegs)*>
<!ELEMENT reset (sfr | UnusedRegs)*>
<!ELEMENT oscillator (sfr | UnusedRegs)*>
<!ELEMENT PMD (sfr | UnusedRegs)*>
<!ELEMENT MSSP (sfr | UnusedRegs)*>
<!ELEMENT CCP (sfr | UnusedRegs)*>
<!ELEMENT VoltageRef (sfr | UnusedRegs)*>
<!ELEMENT Comparator (sfr | UnusedRegs)*>
<!ELEMENT EMI (sfr | UnusedRegs)*>
<!ELEMENT PSP (sfr | UnusedRegs)*>
<!ELEMENT TwoPhasePWM (sfr | UnusedRegs)*>
<!ELEMENT EEPROM (sfr | UnusedRegs)*>
<!ELEMENT OpAmp (sfr | UnusedRegs)*>

<!ELEMENT sfr (field*)>
<!ATTLIST sfr
  key CDATA #REQUIRED
  addr CDATA #REQUIRED
  por CDATA #IMPLIED
  mclr CDATA #IMPLIED
  size CDATA #IMPLIED
  flags CDATA #IMPLIED
  desc CDATA #IMPLIED
>
<!-- Most <sfr> elements have @por and @mclr, while a few have @size and -->
<!-- @flags, and even fewer have @desc.  Seems to me we need two entirely -->
<!-- different elements here so we can tighten requirements on the -->
<!-- attribute list.  Note that the vocab handler ignores the @size, -->
<!-- @flags, and @desc attributes. -->

<!ELEMENT UnusedRegs EMPTY>
<!ATTLIST UnusedRegs addr CDATA #REQUIRED>

<!ELEMENT field (settings*)>
<!ATTLIST field
  key CDATA #REQUIRED
  mask CDATA #REQUIRED
  desc CDATA #REQUIRED
  instance CDATA #IMPLIED
  bits CDATA #IMPLIED
>
<!-- The existing XML documents written in this vocab are a little sloppy -->
<!-- with with presence/absence of the @instance attribute.  We could -->
<!-- tighten this DTD if we wrote it in or decided upon a suitable default -->
<!-- value. -->

<!ELEMENT settings (setting+)>

<!ELEMENT setting EMPTY>
<!ATTLIST setting
  reg CDATA #REQUIRED
  value CDATA #REQUIRED
  desc CDATA #REQUIRED
>

<!ELEMENT deviceConfigurationRegisters (cfgbits*)>

<!ELEMENT cfgbits (field+)>
<!ATTLIST cfgbits
  key CDATA #REQUIRED
  addr CDATA #REQUIRED
  unused CDATA #REQUIRED
  por CDATA #REQUIRED
>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/PIC18F6x2x+PIC18F8x2x ConfigurationRegisters.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configurationRegisters SYSTEM "../configurationRegisters.dtd">
<configurationRegisters>

  <specialFunctionRegisters>

    <CPUCore>
      <sfr key="WREG" addr="0x0FFF" por="xxxxxxxxxxxxxxxx" mclr="uuuuuuuuuuuuuuuu"></sfr>
    </CPUCore>

    <InterruptControl>
      <sfr key="INTCON" addr="0xFF2" por="0000000000000000" mclr="0000000000000000">
        <field key="GIE" instance="1" mask="0x0080" desc=""></field>
        <field key="PEIE" instance="1" mask="0x0040" desc=""></field>
        <field key="TMR0IE" instance="1" mask="0x0020" desc=""></field>
        <field key="T0IE" instance="1" mask="0x0020" desc=""></field>
        <field key="INT0IE" instance="1" mask="0x0010" desc=""></field>
        <field key="RBIE" instance="1" mask="0x0008" desc=""></field>
        <field key="TMR0IF" instance="1" mask="0x0004" desc=""></field>
        <field key="T0IF" instance="1" mask="0x0004" desc=""></field>
        <field key="INT0IF" instance="1" mask="0x0002" desc=""></field>
        <field key="RBIF" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="INTCON2" addr="0xFF1" por="1111111111111111" mclr="0000000000000000">
        <field key="RBPU" instance="1" mask="0x0080" desc=""></field>
        <field key="INTEDG0" instance="1" mask="0x0040" desc=""></field>
        <field key="INTEDG1" instance="1" mask="0x0020" desc=""></field>
        <field key="INTEDG2" instance="1" mask="0x0010" desc=""></field>
        <field key="INTEDG3" instance="1" mask="0x0008" desc=""></field>
        <field key="TMR0IP" instance="1" mask="0x0004" desc=""></field>
        <field key="T0IP" instance="1" mask="0x0004" desc=""></field>
        <field key="INT3IP" instance="1" mask="0x0002" desc=""></field>
        <field key="RBIP" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="INTCON3" addr="0xFF0" por="0000000011000000" mclr="0000000000000000">
        <field key="INT2IP" instance="1" mask="0x0080" desc=""></field>
        <field key="INT1IP" instance="1" mask="0x0040" desc=""></field>
        <field key="INT3IE" instance="1" mask="0x0020" desc=""></field>
        <field key="INT2IE" instance="1" mask="0x0010" desc=""></field>
        <field key="INT1IE" instance="1" mask="0x0008" desc=""></field>
        <field key="INT3IF" instance="1" mask="0x0004" desc=""></field>
        <field key="INT2IF" instance="1" mask="0x0002" desc=""></field>
        <field key="INT1IF" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="IPR3" addr="0xFA5" por="1111111111111111" mclr="0000000000000000">
        <field key="SSP2IP" instance="1" mask="0x0080" desc=""></field>
        <field key="BCL2IP" instance="1" mask="0x0040" desc=""></field>
        <field key="RC2IP" instance="1" mask="0x0020" desc=""></field>
        <field key="TX2IP" instance="1" mask="0x0010" desc=""></field>
        <field key="U2TXIP" instance="1" mask="0x0010" desc=""></field>
        <field key="TMR4IP" instance="1" mask="0x0008" desc=""></field>
        <field key="T4IP" instance="1" mask="0x0008" desc=""></field>
        <field key="CCP5IP" instance="1" mask="0x0004" desc=""></field>
        <field key="CCP4IP" instance="1" mask="0x0002" desc=""></field>
        <field key="CCP3IP" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="PIR3" addr="0xFA4" por="0000000000000000" mclr="0000000000000000">
        <field key="SSP2IF" instance="1" mask="0x0080" desc=""></field>
        <field key="BCL2IF" instance="1" mask="0x0040" desc=""></field>
        <field key="RC2IF" instance="1" mask="0x0020" desc=""></field>
        <field key="U2RXIP" instance="1" mask="0x0020" desc=""></field>
        <field key="TX2IF" instance="1" mask="0x0010" desc=""></field>
        <field key="U2TXIF" instance="1" mask="0x0010" desc=""></field>
        <field key="TMR4IF" instance="1" mask="0x0008" desc=""></field>
        <field key="T4IF" instance="1" mask="0x0008" desc=""></field>
        <field key="CCP5IF" instance="1" mask="0x0004" desc=""></field>
        <field key="CCP4IF" instance="1" mask="0x0002" desc=""></field>
        <field key="CCP3IF" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="PIE3" addr="0xFA3" por="0000000000000000" mclr="0000000000000000">
        <field key="SSP2IE" instance="1" mask="0x0080" desc=""></field>
        <field key="BCL2IE" instance="1" mask="0x0040" desc=""></field>
        <field key="RC2IE" instance="1" mask="0x0020" desc=""></field>
        <field key="U2RXIE" instance="1" mask="0x0020" desc=""></field>
        <field key="TX2IE" instance="1" mask="0x0010" desc=""></field>
        <field key="U2TXIE" instance="1" mask="0x0010" desc=""></field>
        <field key="TMR4IE" instance="1" mask="0x0008" desc=""></field>
        <field key="T4IE" instance="1" mask="0x0008" desc=""></field>
        <field key="CCP5IE" instance="1" mask="0x0004" desc=""></field>
        <field key="CCP4IE" instance="1" mask="0x0002" desc=""></field>
        <field key="CCP3IE" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="IPR2" addr="0xFA2" por="1111111111111111" mclr="0000000000000000">
        <field key="OSCFIP" instance="1" mask="0x0080" desc=""/>
        <field key="CMIP" instance="1" mask="0x0040" desc=""/>
        <field key="reserved" instance="1" mask="0x0020" desc=""/>
        <field key="EEIP" instance="1" mask="0x0010" desc=""/>
        <field key="BCLIP" instance="1" mask="0x0008" desc=""/>
        <field key="LVDIP" instance="1" mask="0x0004" desc=""/>
        <field key="TMR3IP" instance="1" mask="0x0002" desc=""/>
        <field key="T3IP" instance="1" mask="0x0002" desc=""/>
        <field key="CCP2IP" instance="1" mask="0x0001" desc=""/>
      </sfr>
      <sfr key="PIR2" addr="0xFA1" por="0000000000000000" mclr="0000000000000000">
        <field key="OSCFIF" instance="1" mask="0x0080" desc=""/>
        <field key="CMIF" instance="1" mask="0x0040" desc=""/>
        <field key="reserved" instance="1" mask="0x0020" desc=""/>
        <field key="EEIF" instance="1" mask="0x0010" desc=""/>
        <field key="BCLIF" instance="1" mask="0x0008" desc=""/>
        <field key="LVDIF" instance="1" mask="0x0004" desc=""/>
        <field key="TMR3IF" instance="1" mask="0x0002" desc=""/>
        <field key="T3IF" instance="1" mask="0x0002" desc=""/>
        <field key="CCP2IF" instance="1" mask="0x0001" desc=""/>
      </sfr>
      <sfr key="PIE2" addr="0xFA0" por="0000000000000000" mclr="0000000000000000">
        <field key="OSCFIE" instance="1" mask="0x0080" desc=""/>
        <field key="CMIE" instance="1" mask="0x0040" desc=""/>
        <field key="reserved" instance="1" mask="0x0020" desc=""/>
        <field key="EEIE" instance="1" mask="0x0010" desc=""/>
        <field key="BCLIE" instance="1" mask="0x0008" desc=""/>
        <field key="LVDIE" instance="1" mask="0x0004" desc=""/>
        <field key="TMR3IE" instance="1" mask="0x0002" desc=""/>
        <field key="T3IE" instance="1" mask="0x0002" desc=""/>
        <field key="CCP2IE" instance="1" mask="0x0001" desc=""/>
      </sfr>
      <sfr key="IPR1" addr="0xF9F" por="1111111111111111" mclr="0000000000000000">
        <field key="PSPIP" instance="1" mask="0x0080" desc=""></field>
        <field key="ADIP" instance="1" mask="0x0040" desc=""></field>
        <field key="RCIP" instance="1" mask="0x0020" desc=""></field>
        <field key="U1RXIP" instance="1" mask="0x0020" desc=""></field>
        <field key="TXIP" instance="1" mask="0x0010" desc=""></field>
        <field key="U1TXIP" instance="1" mask="0x0010" desc=""></field>
        <field key="SSP1IP" instance="1" mask="0x0008" desc=""></field>
        <field key="CCP1IP" instance="1" mask="0x0004" desc=""></field>
        <field key="TMR2IP" instance="1" mask="0x0002" desc=""></field>
        <field key="T2IP" instance="1" mask="0x0002" desc=""></field>
        <field key="TMR1IP" instance="1" mask="0x0001" desc=""></field>
        <field key="T1IP" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="PIR1" addr="0xF9E" por="0000000000000000" mclr="0000000000000000">
        <field key="PSPIF" instance="1" mask="0x0080" desc=""></field>
        <field key="ADIF" instance="1" mask="0x0040" desc=""></field>
        <field key="RCIF" instance="1" mask="0x0020" desc=""></field>
        <field key="TXIF" instance="1" mask="0x0010" desc=""></field>
        <field key="U1TXIF" instance="1" mask="0x0010" desc=""></field>
        <field key="SSP1IF" instance="1" mask="0x0008" desc=""></field>
        <field key="CCP1IF" instance="1" mask="0x0004" desc=""></field>
        <field key="TMR2IF" instance="1" mask="0x0002" desc=""></field>
        <field key="T2IF" instance="1" mask="0x0002" desc=""></field>
        <field key="TMR1IF" instance="1" mask="0x0001" desc=""></field>
        <field key="T1IF" instance="1" mask="0x0001" desc=""></field>
      </sfr>
      <sfr key="PIE1" addr="0xF9D" por="0000000000000000" mclr="0000000000000000">
        <field key="PSPIE" instance="1" mask="0x0080" desc=""></field>
        <field key="ADIE" instance="1" mask="0x0040" desc=""></field>
        <field key="RCIE" instance="1" mask="0x0020" desc=""></field>
        <field key="U1RXIE" instance="1" mask="0x0020" desc=""></field>
        <field key="TXIE" instance="1" mask="0x0010" desc=""></field>
        <field key="U1TXIE" instance="1" mask="0x0010" desc=""></field>
        <field key="SSP1IE" instance="1" mask="0x0008" desc=""></field>
        <field key="CCP1IE" instance="1" mask="0x0004" desc=""></field>
        <field key="TMR2IE" instance="1" mask="0x0002" desc=""></field>
        <field key="T2IE" instance="1" mask="0x0002" desc=""></field>
        <field key="TMR1IE" instance="1" mask="0x0001" desc=""></field>
