=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/deviceDefinitions.dtd
<!-- This is a DTD for the <deficeDefinitions> vocabulary as we received it -->
<!-- from Sunrise.  I changed the XML documents in only one way in order to -->
<!-- write a slightly tighter DTD: I removed @comment attributes from both -->
<!-- the <operatingTemperature> and <group> elements and replaced them with -->
<!-- regular XML comments. -->

<!-- There are a number of attributes that the vocabulary handler -->
<!-- completely ignores, but are in the documents nonetheless.  I have -->
<!-- marked these attributes with an 'ignored' comment down below. -->

<!ELEMENT deviceDefinitions (
  (dynamicDutyMap?), operatingTemperature, memory, resources, packageList,
  codeTemplate, errata, dataSheet, programRef, familyRef, features, features
)>
<!ATTLIST deviceDefinitions
  name CDATA #REQUIRED
  rev CDATA #REQUIRED
  type CDATA #REQUIRED
  family CDATA #REQUIRED
>

<!ELEMENT operatingTemperature (temperature+)>

<!ELEMENT temperature (voltage+)>
<!ATTLIST temperature minmax CDATA #REQUIRED>

<!ELEMENT voltage (frequency+)>
<!ATTLIST voltage minmax CDATA #REQUIRED>

<!ELEMENT frequency EMPTY>
<!ATTLIST frequency minmax CDATA #REQUIRED>

<!ELEMENT memory EMPTY>
<!ATTLIST memory
  RAM CDATA #REQUIRED
  programFLASH CDATA #REQUIRED
  EEPROM CDATA #REQUIRED
>

<!ELEMENT resources (pinDefinitions, interrupts, configurationRegisters)>

<!ELEMENT pinDefinitions EMPTY>
<!ATTLIST pinDefinitions name CDATA #REQUIRED>

<!ELEMENT interrupts EMPTY>
<!ATTLIST interrupts
  name CDATA #REQUIRED
  IVTStart CDATA #REQUIRED
  AIVTStart CDATA #REQUIRED
  SFRAddressSize CDATA #REQUIRED
>
<!-- Note: @IVTStart, @AIVTStart, and @SFRAddressSize are all ignored by -->
<!-- the vocab handler. -->

<!ELEMENT configurationRegisters EMPTY>
<!ATTLIST configurationRegisters name CDATA #REQUIRED>

<!ELEMENT packageList (type+)>

<!ELEMENT type EMPTY>
<!ATTLIST type name CDATA #REQUIRED>

<!ELEMENT codeTemplate EMPTY>
<!ATTLIST codeTemplate name CDATA #REQUIRED>

<!ELEMENT errata EMPTY>
<!ATTLIST errata name CDATA #REQUIRED>

<!ELEMENT dataSheet EMPTY>
<!ATTLIST dataSheet name CDATA #REQUIRED>

<!ELEMENT programRef EMPTY>
<!ATTLIST programRef name CDATA #REQUIRED>

<!ELEMENT familyRef EMPTY>
<!ATTLIST familyRef name CDATA #REQUIRED>

<!ELEMENT features (group*)>
<!ATTLIST features
  type CDATA #REQUIRED
>

<!ELEMENT group (feature*)>
<!ATTLIST group
  name CDATA #REQUIRED
  type CDATA #IMPLIED
  caption CDATA #IMPLIED
  oldtype CDATA #IMPLIED
>
<!-- Note: The @oldtype attribute is ignored by the vocab handler. -->

<!ELEMENT feature EMPTY>
<!ATTLIST feature
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
  file CDATA #REQUIRED
  feature CDATA #REQUIRED
  image CDATA #REQUIRED
  instance CDATA #IMPLIED
  oldinstance CDATA #IMPLIED
>
<!-- Note: Both @instance and @oldinstance are ignored by the vocab -->
<!-- handler. -->

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/PIC18F2620.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?> 
<!DOCTYPE deviceDefinitions SYSTEM "deviceDefinitions.dtd">

<deviceDefinitions name="PIC18F2620" rev="A" type="8-bit MCU" family="GP">

  <operatingTemperature>
    <temperature minmax="-40 degC, +85 degC">
      <voltage minmax="2.5V, 5.5V">
        <frequency minmax="0 MHz, 40 MHz"/>
      </voltage>
      <voltage minmax="4.5V, 5.5V">
        <frequency minmax="0 MHz, 40 MHz"/>
      </voltage>
    </temperature>
    <temperature minmax="-40 degC, +125 degC">
      <voltage minmax="4.5V, 5.5V">
        <frequency minmax="0 MHz, 40 MHz"/>
      </voltage>
    </temperature>
  </operatingTemperature>

  <memory RAM="3986" programFLASH="65536" EEPROM="1024"/>

  <resources>
    <pinDefinitions name="PIC18/PIC18F2x2x 28-Pin SDIP PinsDefinitions"/>
    <!-- TEMP: Research the interrupts available on this device. -->
    <interrupts name="PIC18/PIC18F4520 Interrupts" IVTStart="" AIVTStart="" SFRAddressSize=""/>
    <configurationRegisters name="PIC18/PIC18F4620 ConfigurationRegisters"/>
  </resources>

  <packageList>
    <type name="28-Pin SDIP"/>
  </packageList>

  <codeTemplate name="PIC18/PIC18F4620 CodeTemplate"/>

  <errata name="*80200*"/>
  <dataSheet name="*39626*"/>
  <programRef name="PIC18Fxx20 ProgrammersReferenceManual"/>
  <familyRef name="PIC18Fxx20 FamilyReferenceManual"/>

  <features type="required">
    <group name="integration" type="integration" caption="integration">
      <feature name="Oscillator2" oldinstance="1" caption="Oscillator" file="PIC18/Oscillator2" feature="Oscillator2" image="oscillator"/>
    </group>
    <group name="integration" type="integration" caption="integration">
      <feature name="Interrupts18" caption="Interrupts and Traps" file="PIC18/Interrupts" feature="Interrupts18" image="Interrupts"/>
    </group>
  </features>
  <features type="optional">
    <group name="RTC" type="RTC" caption="RTC">
      <feature name="RTC" oldinstance="1" caption="RTC" file="PIC18/RTC" feature="Timer1" image="RTC"/>
    </group>
    <group name="IOPort" type="IOPort" caption="I/O Ports">
      <feature name="IOPort" instance="A" caption="Port A" file="PIC18/IOPort" feature="IOPortA" image="IOPort"/>
      <feature name="IOPort" instance="B" caption="Port B" file="PIC18/IOPort" feature="IOPortB" image="IOPort"/>
      <feature name="IOPort" instance="C" caption="Port C" file="PIC18/IOPort" feature="IOPortC" image="IOPort"/>
      <feature name="IOPortE" oldinstance="E" caption="Port E" file="PIC18/IOPortE" feature="IOPortE" image="IOPort"/>
    </group>
    <group name="timer" type="Timers" caption="Timers">
      <feature name="16bitZeroTimer" instance="0" caption="16-bit Timer 0" file="PIC18/16bitZeroTimer" feature="Timer0" image="TimerR"/>
      <feature name="16bitTimer" instance="1" caption="16-bit Timer 1" file="PIC18/16bitTimer" feature="Timer1" image="TimerR"/>
      <feature name="16bitTimer" instance="3" caption="16-bit Timer 3" file="PIC18/16bitTimer" feature="Timer3" image="TimerR"/>
      <feature name="8bitZeroTimer" instance="0" caption="8-bit Timer 0" file="PIC18/8bitZeroTimer" feature="Timer0" image="TimerR"/>
      <feature name="8bitTimer" instance="2" caption="8-bit Timer 2" file="PIC18/8bitTimer" feature="Timer2" image="TimerR"/>
    </group>
    <group name="counter" type="Counters" caption="Counters">
      <feature name="16bitZeroCounter" instance="0" caption="16-bit Counter 0" file="PIC18/16bitZeroCounter" feature="counter0" image="Counter"/>
      <feature name="16bitAsyncCounter" instance="1" caption="Async Counter 1" file="PIC18/16bitAsyncCounter" feature="counter1" image="Counter"/>
      <feature name="16bitSyncCounter" instance="1" caption="Sync Counter 1" file="PIC18/16bitSyncCounter" feature="counter1" image="Counter"/>
      <feature name="16bitAsyncCounter" instance="3" caption="Async Counter 3" file="PIC18/16bitAsyncCounter" feature="counter3" image="Counter"/>
      <feature name="16bitSyncCounter" instance="3" caption="Sync Counter 3" file="PIC18/16bitSyncCounter" feature="counter3" image="Counter"/>
      <feature name="8bitZeroCounter" instance="0" caption="8-bit Counter 0" file="PIC18/8bitZeroCounter" feature="counter0" image="Counter"/>
    </group>
    <group name="IC" type="IC" caption="IC">
      <feature name="CCPIC" instance="1" caption="IC 1" file="PIC18/IC" feature="CCPIC1" image="Capture"/>
      <feature name="CCPIC" instance="2" caption="IC 2" file="PIC18/IC" feature="CCPIC2" image="Capture"/>
    </group>
    <group name="OC" type="OC" caption="OC">
      <feature name="CCPOC" instance="1" caption="OC 1" file="PIC18/OC" feature="CCPOC1" image="Compare"/>
      <feature name="CCPOC" instance="2" caption="OC 2" file="PIC18/OC" feature="CCPOC2" image="Compare"/>
      <feature name="Comparator" instance="1" caption="Comparator" file="PIC18/Comparator_AN01_23" feature="Comparator" image="Compare"/>
      <feature name="VoltageRef" instance="1" caption="Cmp Voltage Reference" file="PIC18/VoltageRef" feature="VoltageRef" image="Compare"/>
    </group>
    <group name="PWM" type="PWM" caption="PWM">
      <feature name="CCPPWM" instance="1" caption="PWM" file="PIC18/PWM" feature="PWM1" image="PWM"/>
      <feature name="CCPPWM2" oldinstance="1" caption="PWM" file="PIC18/PWM2" feature="PWM2" image="PWM"/>
    </group>
    <group name="SPI" type="SPI" caption="SPI">
      <feature name="SPI" instance="1" caption="SPI 1" file="PIC18/SPI" feature="SPI1" image="SPI"/>
    </group>
    <group name="I2C" type="I2C" caption="I2C">
      <feature name="I2C" oldinstance="1" caption="I2C" file="PIC18/I2C" feature="I2C" image="I2C"/>
    </group>
    <group name="UART" type="UART" caption="UART">
      <feature name="USART" instance="1" caption="USART 1" file="PIC18/EUSART" feature="USART1" image="UART" /> 
    </group>
    <group name="A2D" type="A2D" caption="A to D">
      <feature name="A2D10bit" oldinstance="1" caption="10-bit A to D" file="PIC18/A2D10bit13ch" feature="A2D10bit" image="ADC"/>
    </group>
    <group name="reset" type="Reset" caption="Reset"> <!-- temp -->
      <feature name="BOR" oldinstance="1" caption="Reset" file="PIC18/BORSW" feature="BOR" image="Brownout"/>
      <feature name="LVD" oldinstance="1" caption="LVD" file="PIC18/LVD" feature="LVD" image="LVD"/>
      <feature name="WDT" oldinstance="1" caption="WDT" file="PIC18/WDT" feature="WDT" image="WDT"/>
    </group>
    <group name="EMI" type="EMI" caption="DMI">
      <feature name="PSP" oldinstance="1" caption="PSP" file="PIC18/PSP" feature="PSP" image="PSP"/>
    </group>
  </features>

</deviceDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/PIC16F785.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE deviceDefinitions SYSTEM "deviceDefinitions.dtd">
<deviceDefinitions name="PIC16F785" rev="A" type="8-bit MCU" family="GP">

  <operatingTemperature>
    <temperature minmax="-40 degC, +85 degC">
      <voltage minmax="2.5V, 5.5V">
        <frequency minmax="0 MHz, 25 MHz"/>
      </voltage>
      <voltage minmax="4.5V, 5.5V">
        <frequency minmax="0 MHz, 25 MHz"/>
      </voltage>
    </temperature>
    <temperature minmax="-40 degC, +125 degC">
      <voltage minmax="4.5V, 5.5V">
        <frequency minmax="0 MHz, 25 MHz"/>
      </voltage>
    </temperature>
  </operatingTemperature>

  <memory RAM="128" programFLASH="2048" EEPROM="256"/>

  <resources>
    <pinDefinitions name="midrange/PIC16F785 20-Pin DIP PinsDefinitions"/>
    <interrupts name="midrange/PIC16F785 Interrupts" IVTStart="" AIVTStart="" SFRAddressSize=""/>
    <configurationRegisters name="midrange/PIC16F785 ConfigurationRegisters"/>
  </resources>

  <packageList>
    <type name="20-Pin PDIP"/>
  </packageList>

  <codeTemplate name="midrange/PIC16F785 CodeTemplate"/>

  <errata name=""/>
  <dataSheet name="*41249*"/>
  <programRef name=""/>
  <familyRef name=""/>

  <features type="required">
    <group name="integration" type="integration" caption="integration">
      <feature name="Oscillator1" caption="Oscillator" file="midrange/Oscillator1" image="oscillator" feature=""/>
      <feature name="InterruptsMid" caption="Interrupts and Traps" file="midrange/Interrupts1" image="Interrupts" feature=""/>
    </group>
  </features>

  <features type="optional">

    <group name="IOPort" type="IOPort" caption="I/O Ports">
      <feature name="IOPortWithPUAndIOC" instance="A" caption="Port A" file="midrange/IOPortWithPUAndIOC" image="IOPort" feature=""/>
      <feature name="IOPort" instance="B" caption="Port B" file="midrange/IOPort" image="IOPort" feature=""/>
      <feature name="IOPort" instance="C" caption="Port C" file="midrange/IOPort" image="IOPort" feature=""/>
    </group>

    <group name="timer" type="Timers" caption="Timers">
      <feature name="8bitZeroTimer" instance="0" caption="8-bit Timer 0" file="midrange/8bitZeroTimer" image="TimerR" feature=""/>
      <feature name="16bitTimer" instance="1" caption="16-bit Timer 1" file="midrange/16bitTimer" image="TimerR" feature=""/>
      <feature name="8bitTimer" instance="2" caption="8-bit Timer 2" file="midrange/8bitTimer" image="TimerR" feature=""/>
    </group>

    <group name="counter" type="Counters" caption="Counters">
      <feature name="8bitZeroCounter" instance="0" caption="8-bit Counter 0" file="midrange/8bitZeroCounter" image="Counter" feature=""/>
      <feature name="16bitCounter" instance="1" caption="Counter 1" file="midrange/16bitCounter" image="Counter" feature=""/>
    </group>

    <group name="OpAmp" type="OpAmp" caption="OpAmp">
      <feature name="OpAmp" instance="1" caption="OpAmp1" file="midrange/OpAmp" image="OpAmp" feature=""/>
      <feature name="OpAmp" instance="2" caption="OpAmp2" file="midrange/OpAmp" image="OpAmp" feature=""/>
    </group>

    <group name="IC" type="IC" caption="IC">
      <feature name="CCPIC" instance="1" caption="IC 1" file="midrange/IC"  image="Capture" feature=""/>
    </group>


    <group name="OC" type="OC" caption="OC">
      <feature name="CCPOC" instance="1" caption="OC 1" file="midrange/OC" image="Compare" feature=""/>
      <feature name="Comparator" instance="1" caption="Comparator 1" file="midrange/Comparator" image="Compare" feature=""/>
      <feature name="Comparator" instance="2" caption="Comparator 2" file="midrange/Comparator" image="Compare" feature=""/>
      <feature name="VoltageRef" instance="1" caption="Voltage Reference" file="midrange/VoltageRef" image="Compare" feature=""/>
    </group>

    <group name="PWM" type="PWM" caption="PWM">
      <feature name="CCPPWM" instance="1" caption="PWM" file="midrange/CCPPWM" image="PWM" feature=""/>
      <feature name="TwoPhasePWM" instance="1" caption="Two-Phase PWM" file="midrange/TwoPhasePWM" image="PWM" feature=""/>
    </group>

    <group name="A2D" type="A2D" caption="A to D">
      <feature name="ADC" instance="1" caption="10-bit A to D" file="midrange/ADC" image="ADC" feature=""/>
    </group>

    <group name="reset" type="Reset" caption="Reset">
      <feature name="BOR" caption="Reset" file="midrange/BOR" image="Brownout" feature=""/>
      <feature name="WDT" caption="WDT" file="midrange/WDT" image="WDT" feature=""/>
    </group>

  </features>

</deviceDefinitions>
