=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/featureDefinitions.dtd
<!-- This DTD describes the <featureDefinitions> vocab as we got it from -->
<!-- Sunrise (almost).  I stripped all of the <codeGen> elements out of the -->
<!-- documents to tighten the DTD.  I did the same with the <dependency> -->
<!-- and <comment> elements.  Whatever they started with that I will never -->
<!-- understand, (might as well start over on those things and have a -->
<!-- cleaner vocab). -->

<!-- What we have here is very loose.  The vocab handler ignores a number -->
<!-- of these elements.  The <userControl> and <claimResource> elements are -->
<!-- way too loosey-goosey for my tastes. -->

<!ELEMENT featureDefinitions (userControlGroup*)>
<!ATTLIST featureDefinitions
  name CDATA #REQUIRED
  iconName CDATA #REQUIRED
  helpIndex CDATA #REQUIRED
>

<!ELEMENT userControlGroup (userControlSubGroup*)>
<!ATTLIST userControlGroup
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
>

<!ELEMENT userControlSubGroup (userControl*)>
<!ATTLIST userControlSubGroup
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
>

<!ELEMENT userControl (dialogConfig?, userAction*)>
<!ATTLIST userControl
  type CDATA #IMPLIED
  name CDATA #IMPLIED
  range CDATA #IMPLIED
  state CDATA #IMPLIED
  value CDATA #IMPLIED
  enableForInt CDATA #IMPLIED
  priorityForInt CDATA #IMPLIED
  edgeForInt CDATA #IMPLIED
>

<!ELEMENT dialogConfig (selection*)>
<!ATTLIST dialogConfig
  type CDATA #REQUIRED
  caption CDATA #REQUIRED
  range CDATA #IMPLIED
>

<!ELEMENT selection EMPTY>
<!ATTLIST selection
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT userAction (claimResource)*>
<!ATTLIST userAction
  name CDATA #IMPLIED
>

<!ELEMENT claimResource EMPTY>
<!ATTLIST claimResource
  type CDATA #REQUIRED
  instance CDATA #IMPLIED
  registerField CDATA #IMPLIED
  method CDATA #IMPLIED
  value CDATA #IMPLIED
  pin CDATA #IMPLIED
  polarity CDATA #IMPLIED
  flag CDATA #IMPLIED
  bitshited  CDATA #IMPLIED
  mask  CDATA #IMPLIED
>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/lvd.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">

<featureDefinitions name="LVD" iconName="LVD" helpIndex="">

<userControlGroup name="none" caption="none">
<userControlSubGroup name="none" caption="none">

<userControl name="applyButton">
<dialogConfig type="applyButton" caption="none"></dialogConfig>
<userAction name="apply">
</userAction>
</userControl>

</userControlSubGroup>
</userControlGroup>

<userControlGroup name="thresholdSettings" caption="Threshold Settings">
<userControlSubGroup name="none" caption="none">

<userControl name="enable">
<dialogConfig type="CK" caption="Enable on Startup"></dialogConfig>
<userAction name="enable">
	<claimResource type="register" registerField="LVDEN" value="1"></claimResource>
</userAction>
<userAction name="disable">
	<claimResource type="register" registerField="LVDEN" value="0"></claimResource>
</userAction>
</userControl>

<userControl name="threshold">
<dialogConfig type="CB" caption="Threshold">
	<selection name="19V" value="2.0 - 2.12"></selection> 
	<selection name="21V" value="2.2 - 2.33"></selection> 
	<selection name="23V" value="2.4 - 2.54"></selection> 
	<selection name="25V" value="2.5 - 2.65"></selection> 
	<selection name="26V" value="2.7 - 2.86"></selection> 
	<selection name="29V" value="2.8 - 2.97"></selection> 
	<selection name="31V" value="3.0 - 3.18"></selection> 
	<selection name="34V" value="3.3 - 3.50"></selection> 
	<selection name="36V" value="3.5 - 3.71"></selection> 
	<selection name="37V" value="3.6 - 3.82"></selection> 
	<selection name="39V" value="3.8 - 4.03"></selection> 
	<selection name="41V" value="4.0 - 4.24"></selection> 
	<selection name="43V" value="4.2 - 4.45"></selection> 
	<selection name="46V" value="4.5 - 4.77"></selection> 
	<selection name="LVDIN" value="is LVDIN Pin (nom. 1.24V)"></selection> 
</dialogConfig>
<userAction name="LVDIN">
	<claimResource type="register" registerField="LVDL" value="1111"></claimResource>
	<claimResource type="pin" pin="LVDIN" polarity="Inp"></claimResource>
</userAction>
<userAction name="46V">
	<claimResource type="register" registerField="LVDL" value="1110"></claimResource>
</userAction>
<userAction name="43V">
	<claimResource type="register" registerField="LVDL" value="1101"></claimResource>
</userAction>
<userAction name="41V">
	<claimResource type="register" registerField="LVDL" value="1100"></claimResource>
</userAction>
<userAction name="39V">
	<claimResource type="register" registerField="LVDL" value="1011"></claimResource>
</userAction>
<userAction name="37V">
	<claimResource type="register" registerField="LVDL" value="1010"></claimResource>
</userAction>
<userAction name="36V">
	<claimResource type="register" registerField="LVDL" value="1001"></claimResource>
</userAction>
<userAction name="34V">
	<claimResource type="register" registerField="LVDL" value="1000"></claimResource>
</userAction>
<userAction name="31V">
	<claimResource type="register" registerField="LVDL" value="0111"></claimResource>
</userAction>
<userAction name="29V">
	<claimResource type="register" registerField="LVDL" value="0110"></claimResource>
</userAction>
<userAction name="26V">
	<claimResource type="register" registerField="LVDL" value="0101"></claimResource>
</userAction>
<userAction name="25V">
	<claimResource type="register" registerField="LVDL" value="0100"></claimResource>
</userAction>
<userAction name="23V">
	<claimResource type="register" registerField="LVDL" value="0011"></claimResource>
</userAction>
<userAction name="21V">
	<claimResource type="register" registerField="LVDL" value="0010"></claimResource>
</userAction>
<userAction name="19V">
	<claimResource type="register" registerField="LVDL" value="0001"></claimResource>
</userAction>
</userControl>

<userControl name="interruptEnable" enableForInt="LVD">
<dialogConfig type="CK" caption="Enable Interrupt on Startup"></dialogConfig>
<userAction name="enable">
	<claimResource type="register" registerField="LVDIE" value="1"></claimResource>
</userAction>
<userAction name="disable">
	<claimResource type="register" registerField="LVDIE" value="0"></claimResource>
</userAction>
</userControl>

<userControl name="interruptPriority" priorityForInt="LVD">
  <dialogConfig type="CB" caption="Interrupt Priority">
    <selection name="PriorityLevelToHigh" value="High"/>
    <selection name="PriorityLevelToLow" value="Low"/>
  </dialogConfig>
  <userAction>
    <claimResource type="register" registerField="LVDIP" value="0"/>
  </userAction>
  <userAction>
    <claimResource type="register" registerField="LVDIP" value="1"/>
  </userAction>
</userControl>

</userControlSubGroup>
</userControlGroup>

</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/PWM A.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">
<featureDefinitions name="CCPPWM" iconName="PWM" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"></dialogConfig>
        <userAction name="apply">
          <claimResource type="register" registerField="OWN_CCP%instance%" value="11"></claimResource>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="enable">
        <dialogConfig type="CK" caption="Enable on Startup"></dialogConfig>
        <userAction name="enable">
          <claimResource type="register" registerField="CCP%instance%M3" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M2" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M1" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M0" value="0"></claimResource>
        </userAction>
        <userAction name="disable">
        </userAction>
      </userControl>

      <userControl name="alternatePinMX">
        <dialogConfig type="CK" caption="Alternate Pin MX"></dialogConfig>
        <userAction name="enable">
          <claimResource type="register" registerField="CCP%instance%MX" value="0"></claimResource>
          <claimResource type="pin" pin="CCP%instance%MX" polarity="Shared"></claimResource>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="CCP%instance%MX" value="1"></claimResource>
          <claimResource type="pin" pin="CCP%instance%" polarity="Shared"></claimResource>
        </userAction>
      </userControl>

      <userControl name="timeBase">
        <dialogConfig type="CB" caption="Time base">
          <selection name="timer2" value="Timer 2"></selection> 
        </dialogConfig>
        <userAction name="timer2">
</userAction>
      </userControl>

      <userControl type="readOnly" name="period">
        <dialogConfig type="general" caption="Period"></dialogConfig>
        <userAction>
	<!-- TAD=TCY*(0.5*(ADCS[5:0]+1)) -->
	<!-- min=TCY/2, max=32*TCY -->
        </userAction>
      </userControl>

      <userControl type="readOnly" name="desiredDuty">
        <dialogConfig type="general" caption="Desired duty"></dialogConfig>
        <userAction>
	<!-- TAD=TCY*(0.5*(ADCS[5:0]+1)) -->
	<!-- min=TCY/2, max=32*TCY -->
        </userAction>
      </userControl>

      <userControl type="readOnly" name="dutyError">
        <dialogConfig type="general" caption="Duty error"></dialogConfig>
        <userAction>
	<!-- TAD=TCY*(0.5*(ADCS[5:0]+1)) -->
	<!-- min=TCY/2, max=32*TCY -->
        </userAction>
      </userControl>

      <userControl name="interruptEnable">
        <dialogConfig type="CK" caption="Enable Interrupt on Startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="CCP%instance%IE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="CCP%instance%IE" value="0"/>
        </userAction>
      </userControl>

      <userControl name="interruptPriority">
        <dialogConfig type="CB" caption="Interrupt Priority">
          <selection name="txPriorityLevelToHigh" value="High"/>
          <selection name="txPriorityLevelToLow" value="Low"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="CCP%instance%IP" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CCP%instance%IP" value="1"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>
</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/midrange/adc.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">

<featureDefinitions name="ADC" iconName="ADC" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">
      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply"/>
      </userControl>
    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="General" caption="General">
    <userControlSubGroup name="none" caption="none">

      <userControl name="EnableOnStartup">
        <dialogConfig type="CK" caption="Enable on startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="ADON" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="ADON" value="0"/>
        </userAction>
      </userControl>

      <userControl name="EnableInterrupt" enableForInt="AD">
        <dialogConfig type="CK" caption="Enable on startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="ADIE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="ADIE" value="0"/>
        </userAction>
      </userControl>

      <userControl name="ReferenceVoltage">
        <dialogConfig type="CB" caption="Range">
          <selection name="Vdd" value="Vdd"/>
          <selection name="VRefPin" value="VRef Pin"/>
        </dialogConfig>
        <userAction>
          <claimResource type="pin" pin="VREF" polarity="Inp"/>
          <claimResource type="register" registerField="VCFG" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="VCFG" value="0"/>
        </userAction>
      </userControl>

      <userControl name="ResultFormat">
        <dialogConfig type="CB" caption="Range">
          <selection name="LeftJustified" value="Left Justified"/>
          <selection name="RightJustified" value="Right Justified"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="ADFM" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="ADFM" value="0"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="InputChannels" caption="Input Channels">
    <userControlSubGroup name="none" caption="none">

<!-- This representation won't work for us if our code for automatically -->
<!-- generating the TRIS bits fails.  Remember to test that out! -->

      <userControl name="EnableChannel%indexControl%" range="11">
        <dialogConfig type="BoxCK" caption="AN%indexControl%"/>
        <userAction name="enable">
          <claimResource type="register" registerField="ANS%indexControl%" value="1"/>
          <claimResource type="pin" pin="AN%indexControl%" polarity="Inp"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="ANS%indexControl%" value="0"/>
        </userAction>
      </userControl>

      <userControl name="ReadChannel">
        <dialogConfig type="CB" caption="">
          <selection name="Read0" value="AN0"/>
          <selection name="Read1" value="AN1"/>
          <selection name="Read2" value="AN2"/>
          <selection name="Read3" value="AN3"/>
          <selection name="Read4" value="AN4"/>
          <selection name="Read5" value="AN5"/>
          <selection name="Read6" value="AN6"/>
          <selection name="Read7" value="AN7"/>
          <selection name="Read8" value="AN8"/>
          <selection name="Read9" value="AN9"/>
          <selection name="Read10" value="AN10"/>
          <selection name="Read11" value="AN11"/>
          <selection name="ReadCVRef" value="CVRef"/>
          <selection name="Read1.2VNominal" value="1.2V Nominal"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="CHS" value="1101"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="1100"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="1011"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="1010"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="1001"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="1000"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0111"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0110"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0101"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0100"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0011"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0010"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0001"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="CHS" value="0000"/>
        </userAction>
      </userControl>

     </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="Conversion" caption="Conversion">
    <userControlSubGroup name="none" caption="none">

<!-- This control does nothing more than capture the user's intent to use -->
<!-- one type of clock source or the other. -->

      <userControl name="ConversionClockSourceFlavor">
        <dialogConfig type="CB" caption="Conversion Clock Source">
          <selection name="Fosc" value="Fosc Based"/>
          <selection name="ADCIntOsc" value="ADC Internal Oscillator"/>
        </dialogConfig>
        <userAction/>
        <userAction/>
      </userControl>

      <userControl name="ConversionClockSourceSelect">
        <dialogConfig type="CB" caption="Conversion Clock Source Select">
          <selection name="FoscBy2" value="Fosc/2"/>
          <selection name="FoscBy4" value="Fosc/4"/>
          <selection name="FoscBy8" value="Fosc/8"/>
          <selection name="FoscBy16" value="Fosc/16"/>
          <selection name="FoscBy32" value="Fosc/32"/>
          <selection name="FoscBy64" value="Fosc/64"/>
          <selection name="ADRC" value="ADRC (500 kHz)"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="ADCS" value="011"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="ADCS" value="110"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="ADCS" value="010"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="ADCS" value="101"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="ADCS" value="001"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="ADCS" value="100"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="ADCS" value="000"/>
        </userAction>
      </userControl>

      <userControl name="DesiredSamplePeriod">
        <dialogConfig type="TB" caption="Desired Sample Period"/>
        <userAction/>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/16bitZeroTimer.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">
<featureDefinitions name="16bitZeroTimer" iconName="16bitTimer" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply">
          <claimResource type="register" instance="%instance%" registerField="OWN_TMR" value="1100"/>
          <claimResource type="register" registerField="T%instance%8BIT" value="0"/>
          <claimResource type="register" registerField="T%instance%CS" value="0"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="enable">
        <dialogConfig type="CK" caption="Enable on Startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="TMR%instance%ON" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="TMR%instance%ON" value="0"/>
        </userAction>
      </userControl>

      <userControl name="prescale">
        <dialogConfig type="CB" caption="Time Clock Prescale">
          <selection name="setTo0" value="1:1"/>
          <selection name="setTo1" value="1:2"/>
          <selection name="setTo2" value="1:4"/>
          <selection name="setTo3" value="1:8"/>
          <selection name="setTo4" value="1:16"/>
          <selection name="setTo5" value="1:32"/>
          <selection name="setTo6" value="1:64"/>
          <selection name="setTo7" value="1:128"/>
          <selection name="setTo8" value="1:256"/>
        </dialogConfig>
        <userAction name="setTo8">
          <claimResource type="register" registerField="T%instance%PS" value="111"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo7">
          <claimResource type="register" registerField="T%instance%PS" value="110"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo6">
          <claimResource type="register" registerField="T%instance%PS" value="101"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo5">
          <claimResource type="register" registerField="T%instance%PS" value="100"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo4">
          <claimResource type="register" registerField="T%instance%PS" value="011"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo3">
          <claimResource type="register" registerField="T%instance%PS" value="010"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo2">
          <claimResource type="register" registerField="T%instance%PS" value="001"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo1">
          <claimResource type="register" registerField="T%instance%PS" value="000"/>
          <claimResource type="register" instance="%instance%" registerField="PSA" value="0"/>
        </userAction>
        <userAction name="setTo0">
          <claimResource type="register" instance="%instance%" registerField="PSA" value="1"/>
        </userAction>
      </userControl>

<!-- timerPeriod is currently hardcoded and should not be present -->

      <userControl type="readOnly" name="timerFrequency">
        <dialogConfig type="general" caption="Baud Rate Error (%)"/>
        <userAction>
        </userAction>
      </userControl>

      <userControl name="interruptEnable" enableForInt="T0">
        <dialogConfig type="CK" caption="Enable Interrupt on Startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="T0IE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="T0IE" value="0"/>
        </userAction>
      </userControl>

      <userControl name="interruptPriority" priorityForInt="T0">
        <dialogConfig type="CB" caption="Interrupt Priority">
          <selection name="priorityLevelToHigh" value="High"/>
          <selection name="priorityLevelToLow" value="Low"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="T0IP" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="T0IP" value="1"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>
