=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/featureDefinitions.dtd
<!-- This DTD describes the <featureDefinitions> vocab as we got it from -->
<!-- Sunrise (almost).  I stripped all of the <codeGen> elements out of the -->
<!-- documents to tighten the DTD.  I did the same with the <dependency> -->
<!-- and <comment> elements.  Whatever they started with that I will never -->
<!-- understand, (might as well start over on those things and have a -->
<!-- cleaner vocab). -->

<!-- What we have here is very loose.  The vocab handler ignores a number -->
<!-- of these elements.  The <userControl> and <claimResource> elements are -->
<!-- way too loosey-goosey for my tastes. -->

<!ELEMENT featureDefinitions (userControlGroup*)>
<!ATTLIST featureDefinitions
  name CDATA #REQUIRED
  iconName CDATA #REQUIRED
  helpIndex CDATA #REQUIRED
>

<!ELEMENT userControlGroup (userControlSubGroup*)>
<!ATTLIST userControlGroup
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
>

<!ELEMENT userControlSubGroup (userControl*)>
<!ATTLIST userControlSubGroup
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
>

<!ELEMENT userControl (dialogConfig?, userAction*)>
<!ATTLIST userControl
  type CDATA #IMPLIED
  name CDATA #IMPLIED
  range CDATA #IMPLIED
  state CDATA #IMPLIED
  value CDATA #IMPLIED
  enableForInt CDATA #IMPLIED
  priorityForInt CDATA #IMPLIED
  edgeForInt CDATA #IMPLIED
>

<!ELEMENT dialogConfig (selection*)>
<!ATTLIST dialogConfig
  type CDATA #REQUIRED
  caption CDATA #REQUIRED
  range CDATA #IMPLIED
>

<!ELEMENT selection EMPTY>
<!ATTLIST selection
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT userAction (claimResource)*>
<!ATTLIST userAction
  name CDATA #IMPLIED
>

<!ELEMENT claimResource EMPTY>
<!ATTLIST claimResource
  type CDATA #REQUIRED
  instance CDATA #IMPLIED
  registerField CDATA #IMPLIED
  method CDATA #IMPLIED
  value CDATA #IMPLIED
  pin CDATA #IMPLIED
  polarity CDATA #IMPLIED
  flag CDATA #IMPLIED
  bitshited  CDATA #IMPLIED
  mask  CDATA #IMPLIED
>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/oc.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">
<featureDefinitions name="CCPOC" iconName="OC" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"></dialogConfig>
        <userAction name="apply">
          <claimResource type="register" registerField="OWN_CCP%instance%" value="10"></claimResource>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="mode">
        <dialogConfig type="CB" caption="Mode">
          <selection name="disable" value="Disable"></selection> 
          <selection name="lowToHigh" value="CCPx pin low to high"></selection> 
          <selection name="highToLow" value="CCPx pin high to low"></selection> 
          <selection name="interrupt" value="Generate interrupt only"></selection> 
          <selection name="timerReset" value="Timer reset (CCP1,2) or interrupt only"></selection> 
          <selection name="toggleOutput" value="Toggle Output"></selection> 
        </dialogConfig>
        <userAction name="toggleOutput">
          <claimResource type="register" registerField="CCP%instance%M3" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M2" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M1" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M0" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%IF" value="1"></claimResource>
          <claimResource type="pin" pin="CCP%instance%" polarity="Out"></claimResource>
        </userAction>
        <userAction name="timerReset">
          <claimResource type="register" registerField="CCP%instance%M3" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M2" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M1" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M0" value="1"></claimResource>
        </userAction>
        <userAction name="interrupt">
          <claimResource type="register" registerField="CCP%instance%M3" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M2" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M1" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M0" value="0"></claimResource>
        </userAction>
        <userAction name="highToLow">
          <claimResource type="register" registerField="CCP%instance%M3" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M2" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M1" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M0" value="1"></claimResource>
          <claimResource type="pin" pin="CCP%instance%" polarity="Out"></claimResource>
        </userAction>
        <userAction name="lowToHigh">
          <claimResource type="register" registerField="CCP%instance%M3" value="1"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M2" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M1" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M0" value="0"></claimResource>
          <claimResource type="pin" pin="CCP%instance%" polarity="Out"></claimResource>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="CCP%instance%M3" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M2" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M1" value="0"></claimResource>
          <claimResource type="register" registerField="CCP%instance%M0" value="0"></claimResource>
        </userAction>
      </userControl>

      <userControl name="timeBase">
        <dialogConfig type="CB" caption="Time base">
          <selection name="timer1" value="Timer 1"></selection> 
          <selection name="timer3" value="Timer 3"></selection> 
        </dialogConfig>
        <userAction name="timer3"></userAction>
        <userAction name="timer1"></userAction>
      </userControl>

      <userControl type="readOnly" name="compareValue">
        <dialogConfig type="general" caption="Compare value"></dialogConfig>
        <userAction>
        </userAction>
      </userControl>

      <userControl name="interruptEnable" enableForInt="CCP%instance%">
        <dialogConfig type="CK" caption="Enable Interrupt on Startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="CCP%instance%IE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="CCP%instance%IE" value="0"/>
        </userAction>
      </userControl>

      <userControl name="interruptPriority" priorityForInt="CCP%instance%">
        <dialogConfig type="CB" caption="Interrupt Priority">
          <selection name="txPriorityLevelToHigh" value="High"/>
          <selection name="txPriorityLevelToLow" value="Low"/>
        </dialogConfig>
        <userAction name="txPriorityLevelToLow">
          <claimResource type="register" registerField="CCP%instance%IP" value="0"/>
        </userAction>
        <userAction name="txPriorityLevelToHigh">
          <claimResource type="register" registerField="CCP%instance%IP" value="1"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/IOPortE.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd"[]>
<featureDefinitions name="IOPort" iconName="IOPort" helpIndex="">
	<userControlGroup name="none" caption="none">
		<userControlSubGroup name="none" caption="none">
			<userControl name="applyButton">
				<dialogConfig type="applyButton" caption="none"></dialogConfig>
				<userAction name="apply"></userAction>
			</userControl>
		</userControlSubGroup>
	</userControlGroup>
	<userControlGroup name="portPinSettings" caption="Port Pin Settings">
		<userControlSubGroup name="RE0" caption="RE0">
			<userControl name="dataDirection0">
				<dialogConfig type="CB" caption="Data Direction 0">
					<selection name="unclaimed" value="Unclaimed"></selection>
					<selection name="input" value="Input"></selection>
					<selection name="output" value="Output"></selection>
				</dialogConfig>
				<userAction name="output">
					<claimResource type="register" registerField="TRISE0" value="0"></claimResource>
					<claimResource type="pin" pin="RE0" polarity="Out"></claimResource>
				</userAction>
				<userAction name="input">
					<claimResource type="register" registerField="TRISE0" value="1"></claimResource>
					<claimResource type="pin" pin="RE0" polarity="Inp"></claimResource>
				</userAction>
				<userAction name="unclaimed">
					<claimResource type="pin" flag="unclaim" pin="RE0" polarity="Out"></claimResource>
				</userAction>
			</userControl>
			<userControl name="initialValue0">
				<dialogConfig type="CB" caption="Initial Value 0">
					<selection name="initValue0" value="0"></selection>
					<selection name="initValue1" value="1"></selection>
				</dialogConfig>
				<userAction name="initValue1">
					<claimResource type="register" registerField="PORTE0" value="1"></claimResource>
					<claimResource type="register" registerField="LATE0" value="1"></claimResource>
				</userAction>
				<userAction name="initValue0">
					<claimResource type="register" registerField="PORTE0" value="0"></claimResource>
					<claimResource type="register" registerField="LATE0" value="0"></claimResource>
				</userAction>
			</userControl>
		</userControlSubGroup>
		<userControlSubGroup name="RE1" caption="RE1">
			<userControl name="dataDirection1">
				<dialogConfig type="CB" caption="Data Direction 1">
					<selection name="unclaimed" value="Unclaimed"></selection>
					<selection name="input" value="Input"></selection>
					<selection name="output" value="Output"></selection>
				</dialogConfig>
				<userAction name="output">
					<claimResource type="register" registerField="TRISE1" value="0"></claimResource>
					<claimResource type="pin" pin="RE1" polarity="Out"></claimResource>
				</userAction>
				<userAction name="input">
					<claimResource type="register" registerField="TRISE1" value="1"></claimResource>
					<claimResource type="pin" pin="RE1" polarity="Inp"></claimResource>
				</userAction>
				<userAction name="unclaimed">
					<claimResource type="pin" flag="unclaim" pin="RE1" polarity="Out"></claimResource>
				</userAction>
			</userControl>
			<userControl name="initialValue1">
				<dialogConfig type="CB" caption="Initial Value 1">
					<selection name="initValue0" value="0"></selection>
					<selection name="initValue1" value="1"></selection>
				</dialogConfig>
				<userAction name="initValue1">
					<claimResource type="register" registerField="PORTE1" value="1"></claimResource>
					<claimResource type="register" registerField="LATE1" value="1"></claimResource>
				</userAction>
				<userAction name="initValue0">
					<claimResource type="register" registerField="PORTE1" value="0"></claimResource>
					<claimResource type="register" registerField="LATE1" value="0"></claimResource>
				</userAction>
			</userControl>
		</userControlSubGroup>
		<userControlSubGroup name="RE2" caption="RE2">
			<userControl name="dataDirection2">
				<dialogConfig type="CB" caption="Data Direction 2">
					<selection name="unclaimed" value="Unclaimed"></selection>
					<selection name="input" value="Input"></selection>
					<selection name="output" value="Output"></selection>
				</dialogConfig>
				<userAction name="output">
					<claimResource type="register" registerField="TRISE2" value="0"></claimResource>
					<claimResource type="pin" pin="RE2" polarity="Out"></claimResource>
				</userAction>
				<userAction name="input">
					<claimResource type="register" registerField="TRISE2" value="1"></claimResource>
					<claimResource type="pin" pin="RE2" polarity="Inp"></claimResource>
				</userAction>
				<userAction name="unclaimed">
					<claimResource type="pin" flag="unclaim" pin="RE2" polarity="Out"></claimResource>
				</userAction>
			</userControl>
			<userControl name="initialValue2">
				<dialogConfig type="CB" caption="Initial Value 2">
					<selection name="initValue0" value="0"></selection>
					<selection name="initValue1" value="1"></selection>
				</dialogConfig>
				<userAction name="initValue1">
					<claimResource type="register" registerField="PORTE2" value="1"></claimResource>
					<claimResource type="register" registerField="LATE2" value="1"></claimResource>
				</userAction>
				<userAction name="initValue0">
					<claimResource type="register" registerField="PORTE2" value="0"></claimResource>
					<claimResource type="register" registerField="LATE2" value="0"></claimResource>
				</userAction>
			</userControl>
		</userControlSubGroup>
		<userControlSubGroup name="RE3" caption="RE3">
			<userControl name="dataDirection3">
				<dialogConfig type="CB" caption="Data Direction 3">
					<selection name="unclaimed" value="Unclaimed"></selection>
					<selection name="input" value="Input"></selection>
				</dialogConfig>
				<userAction name="input">
					<claimResource type="pin" pin="RE3" polarity="Inp"></claimResource>
				</userAction>
				<userAction name="unclaimed">
					<claimResource type="pin" flag="unclaim" pin="RE3" polarity="Inp"></claimResource>
				</userAction>
			</userControl>
			<userControl name="initialValue3">
				<dialogConfig type="CB" caption="Initial Value 3">
					<selection name="initValue0" value="0"></selection>
					<selection name="initValue1" value="1"></selection>
				</dialogConfig>
				<userAction name="initValue1">
					<claimResource type="register" registerField="PORTE3" value="1"></claimResource>
					<claimResource type="register" registerField="LATE3" value="1"></claimResource>
				</userAction>
				<userAction name="initValue0">
					<claimResource type="register" registerField="PORTE3" value="0"></claimResource>
					<claimResource type="register" registerField="LATE3" value="0"></claimResource>
				</userAction>
			</userControl>
		</userControlSubGroup>
	</userControlGroup>
</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/midrange/8bitZeroCounter.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">
<featureDefinitions name="8bitZeroCounter" iconName="16bitCounter" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply">
          <claimResource type="pin" pin="T0CKI" polarity="Inp"/>
          <claimResource type="register" registerField="ANS2" value="0"/>
          <claimResource type="register" registerField="T0CS" value="1"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="General" caption="General">
    <userControlSubGroup name="none" caption="none">

      <userControl name="Prescale">
        <dialogConfig type="CB" caption="Timer Prescale">
          <selection name="setTo0" value="1:1"/>
          <selection name="setTo1" value="1:2"/>
          <selection name="setTo2" value="1:4"/>
          <selection name="setTo3" value="1:8"/>
          <selection name="setTo4" value="1:16"/>
          <selection name="setTo5" value="1:32"/>
          <selection name="setTo6" value="1:64"/>
          <selection name="setTo7" value="1:128"/>
          <selection name="setTo8" value="1:256"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="PS" value="111"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="110"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="101"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="100"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="011"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="010"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="001"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="000"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
      </userControl>

      <userControl name="TriggeringEdge">
        <dialogConfig type="CB" caption="Trigger on Edge">
          <selection name="Falling" value="Falling"/>
          <selection name="Rising" value="Rising"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="T0SE" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="T0SE" value="1"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="Interrupt" caption="Interrupt">
    <userControlSubGroup name="none" caption="none">

      <userControl name="EnableInterrupt" enableForInt="T0">
        <dialogConfig type="CK" caption="Enable Interrupt"/>
        <userAction name="enable">
          <claimResource type="register" registerField="T0IE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="T0IE" value="0"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/Oscillator3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">

<featureDefinitions name="Oscillator3" iconName="oscillator" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply">
          <claimResource type="register" registerField="SCS" value="00"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="primaryOscSettings" caption="Primary Oscillator Settings">
    <userControlSubGroup name="none" caption="none">

      <userControl name="clockFreq">
        <dialogConfig type="TB" caption="System Clock Frequency"/>
        <userAction>
          <!-- this is needed for baud calc and should just be stored -->
        </userAction>
      </userControl>

      <userControl type="readOnly" name="fcy">
        <dialogConfig type="general" caption="fcy"/>
        <userAction>
        </userAction>
      </userControl>

      <userControl name="showAdvanced">
        <dialogConfig type="CK" caption="View Advanced Oscillator Settings"/>
        <userAction name="enable"/>
        <userAction name="disable"/>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="advancedOscSettings" caption="Advanced Oscillator Settings">
    <userControlSubGroup name="none" caption="none">

      <userControl name="primaryMode">
        <dialogConfig type="CB" caption="Primary Oscillator Mode">
          <selection name="setToECIOSPLL" value="ECIOSPLL"/>
          <selection name="setToECIOPLL" value="ECIOPLL"/>
          <selection name="setToHSSPLL" value="HSSPLL"/>
	  <selection name="setToRCIO" value="RCIO"/>
	  <selection name="setToHSPLL4" value="HSPLL"/>
          <selection name="setToECIO" value="ECIO"/>
	  <selection name="setToEC" value="EC"/>
          <selection name="setToRC" value="RC"/>
	  <selection name="setToHS" value="HS"/>
	  <selection name="setToXT" value="XT"/>
          <selection name="setToLP" value="LP"/>
        </dialogConfig>
        <userAction name="setToLP">
          <claimResource type="register" registerField="FOSC" value="0000"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
          <claimResource type="pin" pin="OSC2" polarity="Out"/>
        </userAction>
        <userAction name="setToXT">
          <claimResource type="register" registerField="FOSC" value="0001"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
          <claimResource type="pin" pin="OSC2" polarity="Inp"/>
        </userAction>
        <userAction name="setToHS">
          <claimResource type="register" registerField="FOSC" value="0010"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
          <claimResource type="pin" pin="OSC2" polarity="Inp"/>
        </userAction>
        <userAction name="setToRC">
          <claimResource type="register" registerField="FOSC" value="0011"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
          <claimResource type="pin" pin="CLKO" polarity="Out"/>
        </userAction>
        <userAction name="setToEC">
          <claimResource type="register" registerField="FOSC" value="0100"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
          <claimResource type="pin" pin="CLKO" polarity="Out"/>
        </userAction>
        <userAction name="setToECIO">
          <claimResource type="register" registerField="FOSC" value="0101"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
        </userAction>
        <userAction name="setToHSPLL4">
          <claimResource type="register" registerField="FOSC" value="0110"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
          <claimResource type="pin" pin="OSC2" polarity="Inp"/>
        </userAction>
        <userAction name="setToRCIO">
          <claimResource type="register" registerField="FOSC" value="0111"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
        </userAction>
        <userAction name="setToHSSPLL4">
          <claimResource type="register" registerField="FOSC" value="1110"/>
          <claimResource type="pin" pin="OSC1" polarity="Inp"/>
          <claimResource type="pin" pin="OSC2" polarity="Inp"/>
        </userAction>
        <userAction name="setToECIOPLL">
          <claimResource type="register" registerField="FOSC" value="1100"/>
          <claimResource type="pin" pin="OSC2" polarity="Out"/>
        </userAction>
        <userAction name="setToECIOSPLL">
          <claimResource type="register" registerField="FOSC" value="1101"/>
          <claimResource type="pin" pin="OSC2" polarity="Out"/>
        </userAction>
      </userControl>

      <userControl name="clockSwitching">
        <dialogConfig type="CK" caption="Enable Clock Switching"/>
        <userAction name="enable">
          <claimResource type="register" registerField="OSCSEN-L" value="0"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="OSCSEN-L" value="1"/>
        </userAction>
      </userControl>


    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>
