=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/featureDefinitions.dtd
<!-- This DTD describes the <featureDefinitions> vocab as we got it from -->
<!-- Sunrise (almost).  I stripped all of the <codeGen> elements out of the -->
<!-- documents to tighten the DTD.  I did the same with the <dependency> -->
<!-- and <comment> elements.  Whatever they started with that I will never -->
<!-- understand, (might as well start over on those things and have a -->
<!-- cleaner vocab). -->

<!-- What we have here is very loose.  The vocab handler ignores a number -->
<!-- of these elements.  The <userControl> and <claimResource> elements are -->
<!-- way too loosey-goosey for my tastes. -->

<!ELEMENT featureDefinitions (userControlGroup*)>
<!ATTLIST featureDefinitions
  name CDATA #REQUIRED
  iconName CDATA #REQUIRED
  helpIndex CDATA #REQUIRED
>

<!ELEMENT userControlGroup (userControlSubGroup*)>
<!ATTLIST userControlGroup
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
>

<!ELEMENT userControlSubGroup (userControl*)>
<!ATTLIST userControlSubGroup
  name CDATA #REQUIRED
  caption CDATA #REQUIRED
>

<!ELEMENT userControl (dialogConfig?, userAction*)>
<!ATTLIST userControl
  type CDATA #IMPLIED
  name CDATA #IMPLIED
  range CDATA #IMPLIED
  state CDATA #IMPLIED
  value CDATA #IMPLIED
  enableForInt CDATA #IMPLIED
  priorityForInt CDATA #IMPLIED
  edgeForInt CDATA #IMPLIED
>

<!ELEMENT dialogConfig (selection*)>
<!ATTLIST dialogConfig
  type CDATA #REQUIRED
  caption CDATA #REQUIRED
  range CDATA #IMPLIED
>

<!ELEMENT selection EMPTY>
<!ATTLIST selection
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT userAction (claimResource)*>
<!ATTLIST userAction
  name CDATA #IMPLIED
>

<!ELEMENT claimResource EMPTY>
<!ATTLIST claimResource
  type CDATA #REQUIRED
  instance CDATA #IMPLIED
  registerField CDATA #IMPLIED
  method CDATA #IMPLIED
  value CDATA #IMPLIED
  pin CDATA #IMPLIED
  polarity CDATA #IMPLIED
  flag CDATA #IMPLIED
  bitshited  CDATA #IMPLIED
  mask  CDATA #IMPLIED
>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/midrange/wdt.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">
<featureDefinitions name="WDT" iconName="WDT" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply"/>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="EnableCondition">
        <dialogConfig type="CB" caption="Program enable">
          <selection name="FuseCtrlEnabled" value="Fuse Controlled, Enabled"/>
          <selection name="SoftCtrlEnabled" value="Software Controlled, Enabled"/>
          <selection name="SoftCtrlDisabled" value="Software Controlled, Disabled"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="WDTE" value="0"/>
          <claimResource type="register" registerField="SWDTEN" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTE" value="0"/>
          <claimResource type="register" registerField="SWDTEN" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTE" value="1"/>
        </userAction>
      </userControl>

      <userControl name="Prescale">
        <dialogConfig type="CB" caption="WDT Prescaler">
          <selection name="DivBy32" value="1:32"/>
          <selection name="DivBy64" value="1:64"/>
          <selection name="DivBy128" value="1:128"/>
          <selection name="DivBy256" value="1:256"/>
          <selection name="DivBy512" value="1:512"/>
          <selection name="DivBy1024" value="1:1024"/>
          <selection name="DivBy2048" value="1:2048"/>
          <selection name="DivBy4096" value="1:4096"/>
          <selection name="DivBy8192" value="1:8192"/>
          <selection name="DivBy16384" value="1:16384"/>
          <selection name="DivBy32768" value="1:32768"/>
          <selection name="DivBy65536" value="1:65535"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="1011"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="1010"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="1001"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="1000"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0111"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0110"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0101"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0100"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0011"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0010"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0001"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="WDTPS" value="0000"/>
        </userAction>
      </userControl>

      <userControl name="Postscale">
        <dialogConfig type="CB" caption="WDT Postscaler">
          <selection name="DivBy1" value="1:1"/>
          <selection name="DivBy2" value="1:2"/>
          <selection name="DivBy4" value="1:4"/>
          <selection name="DivBy8" value="1:8"/>
          <selection name="DivBy16" value="1:16"/>
          <selection name="DivBy32" value="1:32"/>
          <selection name="DivBy64" value="1:64"/>
          <selection name="DivBy128" value="1:128"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="PS" value="111"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="110"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="101"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="100"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="011"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="010"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="001"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="000"/>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/psp1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">
<featureDefinitions name="PSP" iconName="PSP" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply">
          <claimResource type="pin" pin="RD0" polarity="Inp"/>
          <claimResource type="pin" pin="RD1" polarity="Inp"/>
          <claimResource type="pin" pin="RD2" polarity="Inp"/>
          <claimResource type="pin" pin="RD3" polarity="Inp"/>
          <claimResource type="pin" pin="RD4" polarity="Inp"/>
          <claimResource type="pin" pin="RD5" polarity="Inp"/>
          <claimResource type="pin" pin="RD6" polarity="Inp"/>
          <claimResource type="pin" pin="RD7" polarity="Inp"/>
          <claimResource type="pin" pin="RE0" polarity="Inp"/>
          <claimResource type="pin" pin="RE1" polarity="Inp"/>
          <claimResource type="pin" pin="RE2" polarity="Inp"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="enable">
        <dialogConfig type="CK" caption="Enable on Startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="PSPMODE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="PSPMODE" value="0"/>
        </userAction>
      </userControl>

      <userControl name="interruptEnable" enableForInt="PSP">
        <dialogConfig type="CK" caption="Enable Interrupt on Startup"/>
        <userAction name="enable">
          <claimResource type="register" registerField="PSPIE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="PSPIE" value="0"/>
        </userAction>
      </userControl>

      <userControl name="interruptPriority" priorityForInt="PSP">
        <dialogConfig type="CB" caption="Interrupt Priority">
          <selection name="priorityLevelToHigh" value="High"/>
          <selection name="priorityLevelToLow" value="Low"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="PSPIP" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PSPIP" value="1"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/midrange/8bitZeroTimer.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">
<featureDefinitions name="8bitZeroTimer" iconName="16bitTimer" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">

      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply">
          <claimResource type="register" registerField="T0CS" value="0"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="TimerPeriod" caption="timer Period">
    <userControlSubGroup name="none" caption="none">

      <userControl name="Prescale">
        <dialogConfig type="CB" caption="Timer Prescale">
          <selection name="setTo0" value="1:1"/>
          <selection name="setTo1" value="1:2"/>
          <selection name="setTo2" value="1:4"/>
          <selection name="setTo3" value="1:8"/>
          <selection name="setTo4" value="1:16"/>
          <selection name="setTo5" value="1:32"/>
          <selection name="setTo6" value="1:64"/>
          <selection name="setTo7" value="1:128"/>
          <selection name="setTo8" value="1:256"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="PS" value="111"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="110"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="101"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="100"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="011"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="010"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="001"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PS" value="000"/>
          <claimResource type="register" registerField="PSA" value="0"/>
        </userAction>
        <userAction>
          <claimResource type="register" registerField="PSA" value="1"/>
        </userAction>
      </userControl>

      <userControl name="DesiredTimerPeriod">
        <dialogConfig type="TB" caption="Desired Timer Period"/>
        <userAction/>
      </userControl>

      <userControl name="Preload">
        <dialogConfig type="CB" caption="Pre-load the TMR0 register" range="255">
          <selection name="Preload%index%" value="%index%"/>
        </dialogConfig>
        <userAction>
          <claimResource type="register" registerField="TMR0" value="%index%"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="Interrupt" caption="Interrupt">
    <userControlSubGroup name="none" caption="none">

      <userControl name="EnableInterrupt" enableForInt="T0">
        <dialogConfig type="CK" caption="Enable Interrupt"/>
        <userAction name="enable">
          <claimResource type="register" registerField="T0IE" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" registerField="T0IE" value="0"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/spi2.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd"[]>
<featureDefinitions name="SPI" iconName="SPI" helpIndex="">
	<userControlGroup name="none" caption="none">
		<userControlSubGroup name="none" caption="none">
			<userControl name="applyButton">
				<dialogConfig type="applyButton" caption="none"></dialogConfig>
				<userAction name="apply">
					<claimResource type="register" registerField="OWN_MSSP%instance%" value="0"></claimResource>
					<claimResource type="pin" pin="SDI%instance%" polarity="Inp"></claimResource>
				</userAction>
			</userControl>
		</userControlSubGroup>
	</userControlGroup>
	<userControlGroup name="communicationSettings" caption="Communication Settings">
		<userControlSubGroup name="none" caption="none">
			<userControl name="enable">
				<dialogConfig type="CK" caption="Enable on Startup"></dialogConfig>
				<userAction name="enable">
					<claimResource type="register" instance="%instance%" registerField="SSPEN" value="1"></claimResource>
				</userAction>
				<userAction name="disable">
					<claimResource type="register" instance="%instance%" registerField="SSPEN" value="0"></claimResource>
				</userAction>
			</userControl>
			<userControl name="enableSDOx">
				<dialogConfig type="CK" caption="Enable Data Out on SDO pin"></dialogConfig>
				<userAction name="disable"></userAction>
				<userAction name="enable">
					<claimResource type="pin" pin="SDO%instance%" polarity="Out"></claimResource>
				</userAction>
			</userControl>
			<userControl name="interruptEnable" enableForInt="SSP%instance%">
				<dialogConfig type="CK" caption="Enable Interrupt on Startup" />
				<userAction name="enable">
					<claimResource type="register" registerField="SSP%instance%IE" value="1" />
				</userAction>
				<userAction name="disable">
					<claimResource type="register" registerField="SSP%instance%IE" value="0" />
				</userAction>
			</userControl>
			<userControl name="interruptPriority" priorityForInt="SSP%instance%">
				<dialogConfig type="CB" caption="Interrupt Priority">
					<selection name="priorityLevelToHigh" value="High" />
					<selection name="priorityLevelToLow" value="Low" />
				</dialogConfig>
				<userAction>
					<claimResource type="register" registerField="SSP%instance%IP" value="0" />
				</userAction>
				<userAction>
					<claimResource type="register" registerField="SSP%instance%IP" value="1" />
				</userAction>
			</userControl>
			<userControl name="idleClockState">
				<dialogConfig type="CB" caption="Idle Clock State">
					<selection name="low" value="IDLE state is low"></selection>
					<selection name="high" value="IDLE state is high"></selection>
				</dialogConfig>
				<userAction name="high">
					<claimResource type="register" instance="%instance%" registerField="CKP" value="1"></claimResource>
				</userAction>
				<userAction name="low">
					<claimResource type="register" instance="%instance%" registerField="CKP" value="0"></claimResource>
				</userAction>
			</userControl>
			<userControl name="transmitClockEdge">
				<dialogConfig type="CB" caption="Transmit Clock Edge">
					<selection name="low" value="Idle clock to Active"></selection>
					<selection name="high" value="Active clock to Idle"></selection>
				</dialogConfig>
				<userAction name="high">
					<claimResource type="register" instance="%instance%" registerField="CKE" value="1"></claimResource>
				</userAction>
				<userAction name="low">
					<claimResource type="register" instance="%instance%" registerField="CKE" value="0"></claimResource>
				</userAction>
			</userControl>
			<userControl name="SPIMode">
				<dialogConfig type="CB" caption="Mode">
					<selection name="MasterWClockby4" value="Master with Fosc/4"></selection>
					<selection name="MasterWClockby16" value="Master with Fosc/16"></selection>
					<selection name="MasterWClockby64" value="Master with Fosc/64"></selection>
					<selection name="MasterWTMR2by2" value="Master with Timer2/2"></selection>
					<selection name="Slave" value="Slave, slave select disabled"></selection>
					<selection name="SlaveSlaveSel" value="Slave, slave select enabled"></selection>
				</dialogConfig>
				<userAction name="SlaveSlaveSel">
					<claimResource type="register" instance="%instance%" registerField="SSPM3" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM2" value="1"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM1" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM0" value="0"></claimResource>
					<claimResource type="pin" pin="SCK%instance%" polarity="Inp"></claimResource>
					<claimResource type="pin" pin="SS%instance%-L" polarity="Inp"></claimResource>
				</userAction>
				<userAction name="Slave">
					<claimResource type="register" instance="%instance%" registerField="SSPM3" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM2" value="1"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM1" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM0" value="1"></claimResource>
					<claimResource type="pin" pin="SCK%instance%" polarity="Inp"></claimResource>
				</userAction>
				<userAction name="MasterWTMR2by2">
					<claimResource type="register" instance="%instance%" registerField="SSPM3" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM2" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM1" value="1"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM0" value="1"></claimResource>
				</userAction>
				<userAction name="MasterWClockby64">
					<claimResource type="register" instance="%instance%" registerField="SSPM3" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM2" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM1" value="1"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM0" value="0"></claimResource>
				</userAction>
				<userAction name="MasterWClockby16">
					<claimResource type="register" instance="%instance%" registerField="SSPM3" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM2" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM1" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM0" value="1"></claimResource>
				</userAction>
				<userAction name="MasterWClockby4">
					<claimResource type="register" instance="%instance%" registerField="SSPM3" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM2" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM1" value="0"></claimResource>
					<claimResource type="register" instance="%instance%" registerField="SSPM0" value="0"></claimResource>
				</userAction>
			</userControl>
		</userControlSubGroup>
		<userControlSubGroup name="masterSettings" caption="Master Settings">
			<userControl name="dataInputPhase">
				<dialogConfig type="CB" caption="Data Input Sample Instant">
					<selection name="middle" value="Middle of data output time"></selection>
					<selection name="end" value="End of data output time"></selection>
				</dialogConfig>
				<userAction name="end">
					<claimResource type="register" instance="%instance%" registerField="SMP" value="1"></claimResource>
				</userAction>
				<userAction name="middle">
					<claimResource type="register" instance="%instance%" registerField="SMP" value="0"></claimResource>
				</userAction>
			</userControl>
			<userControl type="readOnly" name="baudRate">
				<dialogConfig type="general" caption="Baud Rate"></dialogConfig>
				<userAction></userAction>
			</userControl>
		</userControlSubGroup>
	</userControlGroup>
</featureDefinitions>

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/midrange/OpAmp.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE featureDefinitions SYSTEM "../featureDefinitions.dtd">

<featureDefinitions name="OpAmp" iconName="Op Amp" helpIndex="">

  <userControlGroup name="none" caption="none">
    <userControlSubGroup name="none" caption="none">
      <userControl name="applyButton">
        <dialogConfig type="applyButton" caption="none"/>
        <userAction name="apply">
          <claimResource type="pin" pin="OP%instance%+" polarity="Inp"/>
          <claimResource type="pin" pin="OP%instance%-" polarity="Inp"/>
          <claimResource type="pin" pin="OP%instance%" polarity="Out"/>
        </userAction>
      </userControl>
    </userControlSubGroup>
  </userControlGroup>

  <userControlGroup name="Op-Amp Configuration" caption="Op-Amp Configuration">
    <userControlSubGroup name="none" caption="none">

      <userControl name="Enable">
        <dialogConfig type="CK" caption="Enable on startup"/>
        <userAction name="enable">
          <claimResource type="register" instance="%instance%" registerField="OPAON" value="1"/>
        </userAction>
        <userAction name="disable">
          <claimResource type="register" instance="%instance%" registerField="OPAON" value="0"/>
        </userAction>
      </userControl>

    </userControlSubGroup>
  </userControlGroup>

</featureDefinitions>
