=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pinDefinitions.dtd
<!-- This DTD matches up with the <pinDefinitions> vocabulary that we got -->
<!-- from Sunrise.  As with other vocabularies, I deleted the @comment -->
<!-- attribute from an element here and there so I could tighten this DTD. -->

<!-- The semantics of the <connection@port> and <connection@pin> attributes -->
<!-- are not so good in this vocabulary.  We should definitely fix them on -->
<!-- the next revision of this vocabulary. -->

<!ELEMENT pinDefinitions (pin*)>
<!ATTLIST pinDefinitions
  bitmap CDATA #REQUIRED
  height CDATA #REQUIRED
  width CDATA #REQUIRED
  type CDATA #REQUIRED
  numberOfPins CDATA #REQUIRED
  numberOfSides CDATA #REQUIRED
  topLeftX CDATA #REQUIRED
  leftTopY CDATA #REQUIRED
  pinHeight CDATA #REQUIRED
  pinWidth CDATA #REQUIRED
  pinSpacing CDATA #REQUIRED
  pin1Side CDATA #REQUIRED
  pin1Pos CDATA #REQUIRED
>
<!-- Note: Both @pin1Side and @pin1Pos are ignored by the vocab handler. -->

<!ELEMENT pin (connection*)>
<!ATTLIST pin
  number CDATA #REQUIRED
  name CDATA #REQUIRED
  initConnection CDATA #REQUIRED
>

<!ELEMENT connection EMPTY>
<!ATTLIST connection
  type CDATA #REQUIRED
  name CDATA #REQUIRED
  desc CDATA #REQUIRED
  polarity CDATA #REQUIRED
  feature CDATA #IMPLIED
  instance CDATA #IMPLIED
  port CDATA #IMPLIED
  pin CDATA #IMPLIED
>
<!-- Note: Both @feature and @instance are ignored by the vocab handler. -->

=== GreatCowBASIC/DATFileGenerator/MPLAB Files/xml/pic18/PIC18F1x20 20-Pin SSOP PinsDefinitions.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE pinDefinitions SYSTEM "../pinDefinitions.dtd">

<pinDefinitions bitmap="20-Pin SSOP" height="240" width="260" type="SSOP" numberOfPins="20" numberOfSides="2" 
topLeftX="0" leftTopY="17" pinHeight="20" pinWidth="12" pinSpacing="10" pin1Side="0" pin1Pos="0">

<pin number="1" name="RA0/AN0" initConnection="none">
	<connection type="IOPort" name="RA0" feature="IOPort" port="A" pin="0" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
	<connection type="periph" name="AN0" feature="A2D" instance="0" polarity="Inp" desc="Analog Input"></connection>
</pin>

<pin number="2" name="RA1/AN1/LVDIN" initConnection="none">
	<connection type="IOPort" name="RA1" feature="IOPort" port="A" pin="1" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
	<connection type="periph" name="AN1" feature="A2D" instance="1" polarity="Inp" desc="Analog Input"></connection>
	<connection type="other" name="LVDIN" feature="Reset" polarity="Input" desc="Analog Low Voltage Detect Ref Volage Input Pin"></connection>
</pin>

<pin number="3" name="RA4/T0CK" initConnection="none">
	<connection type="IOPort" name="RA4" feature="IOPort" port="A" pin="4" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
	<connection type="periph" name="T0CK" feature="Timer" instance="0" polarity="Inp" desc="Timer 0 exernal clock input"></connection>
</pin>

<pin number="4" name="MCLR-L/VPP/RA5" initConnection="none">
	<connection type="other" name="MCLR-L/VPP" polarity="I/P" desc="Active low Master Reset Input or Programming Voltage Input"></connection>
	<connection type="IOPort" name="RA5" feature="IOPort" port="A" pin="5" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
</pin>

<pin number="5" name="VSS" initConnection="unaccessible">
	<connection type="other" name="VSS" polarity="P" desc="Gnd Ref for Logic and I/O Pins"></connection>
</pin>

<pin number="6" name="AVSS" initConnection="unaccessible">
	<connection type="other" name="AVSS" polarity="P" desc="Gnd Ref for Logic and I/O Pins"></connection>
</pin>

<pin number="7" name="RA2/AN2/VREF-" initConnection="none">
	<connection type="IOPort" name="RA2" feature="IOPort" port="A" pin="2" polarity="I/O" desc="PORTA bidirectional I/O Port Pin 2"></connection>
	<connection type="periph" name="AN2" feature="A2D" instance="1" polarity="Out" desc="Analog Input"></connection>
	<connection type="other" name="VREF-" polarity="Input" desc="Analog Voltage Ref (Low) Input"></connection>
</pin>

<pin number="8" name="RA3/AN3/VREF+" initConnection="none">
	<connection type="IOPort" name="RA3" feature="IOPort" port="A" pin="3" polarity="I/O" desc="PORTA bidirectional I/O Port Pin 3"></connection>
	<connection type="periph" name="AN3" feature="A2D" instance="1" polarity="Out" desc="Analog Input"></connection>
	<connection type="other" name="VREF+" polarity="Input" desc="Analog Voltage Ref (High) Input"></connection>
</pin>

<pin number="9" name="RB0/AN4/INT0" initConnection="none">
	<connection type="IOPort" name="RB0" feature="IOPort" port="B" pin="0" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
	<connection type="periph" name="AN4" feature="A2D" instance="4" polarity="Inp" desc="Analog Input"></connection>
	<connection type="periph" name="INT0" feature="ExtInt" instance="1" polarity="Inp" desc="External Interrupt 1"></connection>
</pin>

<pin number="10" name="RB1/AN5/U1TX/CK1/INT1" initConnection="none">
	<connection type="IOPort" name="RB1" feature="IOPort" port="B" pin="1" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
	<connection type="periph" name="AN5" feature="A2D" instance="1" polarity="Out" desc="Analog Input"></connection>
	<connection type="periph" name="U1TX" feature="UART" instance="1" polarity="Out" desc="UART1 Transmit"></connection>
	<connection type="periph" name="CK1" feature="UART" instance="1" polarity="Out" desc="UART1 Synch clock"></connection>
	<connection type="periph" name="INT1" feature="ExtInt" instance="1" polarity="Inp" desc="External Interrupt 1"></connection>
</pin>

<pin number="11" name="RB4/AN6/U1RX/DT1/KBIO" initConnection="none">
	<connection type="IOPort" name="RB4" feature="IOPort" port="B" pin="4" polarity="I/O" desc="PORT bidirectional I/O Port"></connection>
	<connection type="periph" name="AN6" feature="A2D" instance="1" polarity="Out" desc="Analog Input"></connection>
	<connection type="periph" name="U1RX" feature="UART" instance="1" polarity="Inp" desc="UART1 Receive"></connection>
	<connection type="periph" name="DT1" feature="UART" instance="1" polarity="Inp" desc="UART1 Synch data"></connection>
</pin>

<pin number="12" name="RB5/PGM/KBI1" initConnection="none">
	<connection type="IOPort" name="RB5" feature="IOPort" port="B" pin="5" polarity="I/O" desc="PORT bidirectional I/O Port"></connection>
	<connection type="other" name="PGM" polarity="I/O" desc="In Ckt Serial Programming Data I/O Pin"></connection>
</pin>

<pin number="13" name="RB6/PGC/T1OSO/T1CK/P1C/KBI2" initConnection="none">
	<connection type="IOPort" name="RB6" feature="IOPort" port="B" pin="6" polarity="I/O" desc="PORT bidirectional I/O Port"></connection>
	<connection type="other" name="PGC" polarity="I/O" desc="In Ckt Serial Programming Data I/O Pin"></connection>
	<connection type="periph" name="T1OSO" feature="Timer" instance="1" polarity="Out" desc="Timer 1 oscillator output"></connection>
	<connection type="periph" name="T1CK" feature="Timer" instance="1,3" polarity="Inp" desc="Timer 1,3 exernal clock input"></connection>
</pin>

<pin number="14" name="RB7/PGD/T1OSI/P1D/KBI3" initConnection="none">
	<connection type="IOPort" name="RB7" feature="IOPort" port="B" pin="7" polarity="I/O" desc="PORT bidirectional I/O Port"></connection>
	<connection type="other" name="PGD" polarity="I/O" desc="In Ckt Serial Programming Data I/O Pin"></connection>
	<connection type="periph" name="T1OSI" feature="Timer" instance="1" polarity="Inp" desc="Timer 1 oscillator input"></connection>
</pin>

<pin number="15" name="AVDD" initConnection="unaccessible">
	<connection type="other" name="AVDD" polarity="P" desc="Positive Supply for Logic and I/O"></connection>
</pin>

<pin number="16" name="VDD" initConnection="unaccessible">
	<connection type="other" name="VDD" polarity="P" desc="Positive Supply for Logic and I/O"></connection>
</pin>

<pin number="17" name="OSC2/CLKO/RA6" initConnection="none">
	<connection type="other" name="OSC2" polarity="I/O" desc="Oscillator Crystal Output"></connection>
	<connection type="other" name="CLKO" polarity="Inp" desc="Oscillator Crystal Output"></connection>
	<connection type="IOPort" name="RA6" feature="IOPort" port="A" pin="6" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
</pin>

<pin number="18" name="OSC1/CLKI/RA7" initConnection="none">
	<connection type="other" name="OSC1" polarity="Inp" desc="Oscillator Crystal Input"></connection>
	<connection type="other" name="CLKI" polarity="Inp" desc="Ext Clock Source Input"></connection>
	<connection type="IOPort" name="RA7" feature="IOPort" port="A" pin="7" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
</pin>

<pin number="19" name="RB2/P1B/INT2" initConnection="none">
	<connection type="IOPort" name="RB2" feature="IOPort" port="B" pin="2" polarity="I/O" desc="PORT bidirectional I/O Port Pin"></connection>
	<connection type="periph" name="INT2" feature="ExtInt" instance="1" polarity="Inp" desc="External Interrupt 1"></connection>
</pin>

<pin number="20" name="RB3/INT3/CCP1/P1A" initConnection="none">
	<connection type="IOPort" name="RB3" feature="IOPort" port="B" pin="3" polarity="I/O" desc="PORT bidirectional I/O Port"></connection>
	<connection type="periph" name="INT3" feature="ExtInt" instance="4" polarity="Inp" desc="External Interrupt 1"></connection>
	<connection type="periph" name="CCP1" feature="CCP" instance="1" pin="1" polarity="I/O" desc="Capture in, Compare out, or PWM out"></connection>
</pin>

</pinDefinitions>
